# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish SampleWebApp.sln --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: SampleWebApp
    - name: Deploy to App Engine
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: hardy-rhythm-368703
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Deploy
      uses: GoogleCloudPlatform/appengine-deploy-action@v2
      with:
        project_id: hardy-rhythm-368703
        version: v1
        promote: true
        stop_previous_version: true
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        app_dir: SampleWebApp/bin/Release/net6.0/publish