# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  GCP_REGION: us-central1
  GCP_PROJECT_ID: hardy-rhythm-368703
  GCP_GAR_URL: docker.pkg.dev

jobs:
  build:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish SampleWebApp.sln --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - id: GCPAuth
      name: Authenticate using GCP Workload Identity
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: use gcloud cli
      run: gcloud info

    - name: Docker login
      run: gcloud auth configure-docker ${{ env.GCP_REGION }}-${{ env.GCP_GAR_URL }} -q

    - name: Docker build and push
      run: |
        docker build -f SampleWebApp/docker -t ${{ env.GCP_REGION }}-${{ env.GCP_GAR_URL }}/${{ env.GCP_PROJECT_ID }}/docker-repo/samplewebapp:latest .
        docker push ${{ env.GCP_REGION }}-${{ env.GCP_GAR_URL }}/${{ env.GCP_PROJECT_ID }}/docker-repo/samplewebapp:latest

    # step to deploy the uploaded image to cloud run
    - name: Deploy to Cloud Run
      run: gcloud run deploy samplewebapp --image ${{ env.GCP_REGION }}-${{ env.GCP_GAR_URL }}/${{ env.GCP_PROJECT_ID }}/docker-repo/samplewebapp:latest --platform managed --region ${{ env.GCP_REGION }} --allow-unauthenticated --port 80 --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # - name: Login to GAR
    #   uses: docker/login-action@v3
    #   with: 
    #     registry: us-central1-docker.pkg.dev
    #     username: 'oauth2accesstoken'
    #     password: ${{ steps.GCPAuth.outputs.access_token }}

    # - name: Docker push
    #   uses: docker/build-push-action@v2
    #   env:
    #     GCP_GAR_REPO_LOCATION: ${{ env.GCP_REGION }}-${{ env.GCP_GAR_URL }}/${{ env.GCP_PROJECT_ID }}/docker-repo
    #   with:
    #     context: .
    #     file: ./SampleWebApp/Dockerfile
    #     push: true
    #     tags: ${{ env.GCP_GAR_REPO_LOCATION }}/samplewebapp:latest
    # - name: Deploy to Cloud Run
    #   run: gcloud run deploy samplewebapp --image ${{ env.GCP_GAR_REPO_LOCATION }}/samplewebapp:latest --platform managed --region ${{ env.GCP_REGION }} --allow-unauthenticated