# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish SampleWebApp.sln --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: SampleWebApp
        # A file, directory or wildcard pattern that describes what to upload
        path: SampleWebApp/bin/Release/net6.0/publish/**
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error # optional, default is warn